# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 15:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=50)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('request', models.TextField(max_length=50)),
                ('course_lecturer', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 25, 11, 53782, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=50)),
                ('exeat_type', models.CharField(choices=[('1', 'Home'), ('2', 'Other')], max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('application', models.TextField()),
                ('parent_contact', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 25, 11, 55040, tzinfo=utc))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=50)),
                ('hall', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('request', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 25, 11, 57652, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=60)),
                ('courses', models.ManyToManyField(to='complaints.Course')),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAdmRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=50)),
                ('hall', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('request', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 25, 11, 65124, tzinfo=utc))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('1', 'Student'), ('2', 'Staff')], max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=50)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('application', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 25, 11, 56507, tzinfo=utc))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='specialadmrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile'),
        ),
        migrations.AddField(
            model_name='ppd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile'),
        ),
        migrations.AddField(
            model_name='exeat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile'),
        ),
        migrations.AddField(
            model_name='department',
            name='programs',
            field=models.ManyToManyField(to='complaints.Program'),
        ),
        migrations.AddField(
            model_name='academiccomplaint',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Department'),
        ),
        migrations.AddField(
            model_name='academiccomplaint',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.RequestType'),
        ),
        migrations.AddField(
            model_name='academiccomplaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile'),
        ),
    ]
