# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('request', models.TextField(max_length=50)),
                ('matric', models.CharField(max_length=50)),
                ('course_lecturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserType'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academiccomplaint',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.RequestType'),
        ),
        migrations.AddField(
            model_name='academiccomplaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile'),
        ),
    ]
