# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='academiccomplaint',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Courses'),
        ),
    ]
