# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccomplaint',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.Program'),
        ),
        migrations.AlterField(
            model_name='academiccomplaint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 36, 20, 168850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exeat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 36, 20, 169933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ppd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 36, 20, 172264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='specialadmrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 36, 20, 173148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workstudy',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 15, 36, 20, 171167, tzinfo=utc)),
        ),
    ]
