# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20160523_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(to='complaints.Course'),
        ),
    ]
