# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_department_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccomplaint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 15, 22, 52, 254740, tzinfo=utc)),
        ),
    ]
