# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 19:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0004_auto_20160524_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='StudentProfile',
        ),
        migrations.AlterField(
            model_name='academiccomplaint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 19, 13, 10, 404289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exeat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 19, 13, 10, 406235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ppd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 19, 13, 10, 409075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='specialadmrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 19, 13, 10, 410287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workstudy',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 19, 13, 10, 407587, tzinfo=utc)),
        ),
    ]
