# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20160524_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='category',
        ),
        migrations.AlterField(
            model_name='academiccomplaint',
            name='course_lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.StaffProfile', to_field='full_name'),
        ),
        migrations.AlterField(
            model_name='academiccomplaint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 10, 31, 45, 327164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exeat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 10, 31, 45, 328897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ppd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 10, 31, 45, 331450, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='specialadmrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 10, 31, 45, 332582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='workstudy',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 10, 31, 45, 330228, tzinfo=utc)),
        ),
    ]
