# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_academiccomplaint_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('exeat_type', models.CharField(choices=[('Home', 'Home'), ('Other', 'Other')], max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('application', models.TextField()),
                ('parent_contact', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 5, 24, 14, 17, 28, 801387, tzinfo=utc))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('hall', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('request', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAdmRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('hall', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('request', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('application', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='academiccomplaint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 14, 17, 28, 799397, tzinfo=utc)),
        ),
    ]
