# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_auto_20160525_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccomplaint',
            name='request_type',
            field=models.CharField(choices=[('1', 'Makeup'), ('2', 'Portal'), ('3', 'Special'), ('4', 'Result')], max_length=50),
        ),
        migrations.AlterField(
            model_name='academiccomplaint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 11, 52, 9, 28498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exeat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 11, 52, 9, 30101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ppd',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 11, 52, 9, 32779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='specialadmrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 11, 52, 9, 33611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workstudy',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 11, 52, 9, 31736, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='RequestType',
        ),
    ]
